///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Asseco.CSharp.Sample.Tests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Asseco_CSharp_Sample_TestsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    [RepositoryFolder("2133dcab-a929-4a4e-9a9a-3096109cc5a7")]
    public partial class Asseco_CSharp_Sample_TestsRepository : RepoGenBaseFolder
    {
        static Asseco_CSharp_Sample_TestsRepository instance = new Asseco_CSharp_Sample_TestsRepository();
        Asseco_CSharp_Sample_TestsRepositoryFolders.FrmMainAppFolder _frmmain;
        Asseco_CSharp_Sample_TestsRepositoryFolders.AssecoCSharpSampleAppFolder _assecocsharpsample;
        Asseco_CSharp_Sample_TestsRepositoryFolders.FrmCalculatorAppFolder _frmcalculator;

        /// <summary>
        /// Gets the singleton class instance representing the Asseco_CSharp_Sample_TestsRepository element repository.
        /// </summary>
        [RepositoryFolder("2133dcab-a929-4a4e-9a9a-3096109cc5a7")]
        public static Asseco_CSharp_Sample_TestsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Asseco_CSharp_Sample_TestsRepository() 
            : base("Asseco_CSharp_Sample_TestsRepository", "/", null, 0, false, "2133dcab-a929-4a4e-9a9a-3096109cc5a7", ".\\RepositoryImages\\Asseco_CSharp_Sample_TestsRepository2133dcab.rximgres")
        {
            _frmmain = new Asseco_CSharp_Sample_TestsRepositoryFolders.FrmMainAppFolder(this);
            _assecocsharpsample = new Asseco_CSharp_Sample_TestsRepositoryFolders.AssecoCSharpSampleAppFolder(this);
            _frmcalculator = new Asseco_CSharp_Sample_TestsRepositoryFolders.FrmCalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2133dcab-a929-4a4e-9a9a-3096109cc5a7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FrmMain folder.
        /// </summary>
        [RepositoryFolder("4dd41c1f-6c88-4b48-9b90-cc16062ac928")]
        public virtual Asseco_CSharp_Sample_TestsRepositoryFolders.FrmMainAppFolder FrmMain
        {
            get { return _frmmain; }
        }

        /// <summary>
        /// The AssecoCSharpSample folder.
        /// </summary>
        [RepositoryFolder("9132383b-7ac8-4e49-bfbd-bcac0287c923")]
        public virtual Asseco_CSharp_Sample_TestsRepositoryFolders.AssecoCSharpSampleAppFolder AssecoCSharpSample
        {
            get { return _assecocsharpsample; }
        }

        /// <summary>
        /// The FrmCalculator folder.
        /// </summary>
        [RepositoryFolder("95ccc7a7-3fc7-42a5-8536-86f5b99f257d")]
        public virtual Asseco_CSharp_Sample_TestsRepositoryFolders.FrmCalculatorAppFolder FrmCalculator
        {
            get { return _frmcalculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
    public partial class Asseco_CSharp_Sample_TestsRepositoryFolders
    {
        /// <summary>
        /// The FrmMainAppFolder folder.
        /// </summary>
        [RepositoryFolder("4dd41c1f-6c88-4b48-9b90-cc16062ac928")]
        public partial class FrmMainAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tfirstnameInfo;
            RepoItemInfo _buttonbokInfo;
            RepoItemInfo _brakdanychInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _danezostałtyzapisaneInfo;
            RepoItemInfo _tlastnameInfo;
            RepoItemInfo _tstatusInfo;
            RepoItemInfo _dbegindateInfo;
            RepoItemInfo _bcalculatorInfo;
            RepoItemInfo _noneInfo;

            /// <summary>
            /// Creates a new FrmMain  folder.
            /// </summary>
            public FrmMainAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FrmMain", "/form[@controlname='FrmMain']", parentFolder, 30000, null, true, "4dd41c1f-6c88-4b48-9b90-cc16062ac928", "")
            {
                _tfirstnameInfo = new RepoItemInfo(this, "TFirstName", "text[@controlname='tFirstName']", 30000, null, "333abdd0-105e-426f-9f44-fef60610cea1");
                _buttonbokInfo = new RepoItemInfo(this, "ButtonBOk", "button[@controlname='bOk']", 30000, null, "c11cd780-0d32-4c9e-a507-6eeb7a93ebed");
                _brakdanychInfo = new RepoItemInfo(this, "BrakDanych", "?/?/picture[@accessiblename='Brak danych']", 30000, null, "eb0a96b0-c9f5-40af-b1d7-b140370e8599");
                _textInfo = new RepoItemInfo(this, "Text", "text[@controlname='tFirstName']/text[@accessiblerole='Text']", 30000, null, "dd27a84b-9df6-4840-8c2e-eec629604f23");
                _danezostałtyzapisaneInfo = new RepoItemInfo(this, "DaneZostałtyZapisane", "text[@controlname='lStatus']", 30000, null, "7e094e00-4f17-401a-8ca9-15f567d1d048");
                _tlastnameInfo = new RepoItemInfo(this, "TLastName", "text[@controlname='tLastName']", 30000, null, "2fb17244-f29b-4228-95e2-266a0df2fc7e");
                _tstatusInfo = new RepoItemInfo(this, "TStatus", "text[@controlname='tStatus']", 30000, null, "08f711e1-71d8-4024-9969-76886a2fc684");
                _dbegindateInfo = new RepoItemInfo(this, "DBeginDate", "datetime[@controlname='dBeginDate']", 30000, null, "78fbac79-a3b7-44ef-9e3a-bca2519e9fe8");
                _bcalculatorInfo = new RepoItemInfo(this, "BCalculator", "button[@controlname='bCalculator']", 30000, null, "6d68d03d-f2e5-4d84-8bbf-eaea50194478");
                _noneInfo = new RepoItemInfo(this, "None", "?/?/text", 30000, null, "00c53744-d967-4974-8dcc-09c4754ed002");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4dd41c1f-6c88-4b48-9b90-cc16062ac928")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4dd41c1f-6c88-4b48-9b90-cc16062ac928")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TFirstName item.
            /// </summary>
            [RepositoryItem("333abdd0-105e-426f-9f44-fef60610cea1")]
            public virtual Ranorex.Text TFirstName
            {
                get
                {
                    return _tfirstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TFirstName item info.
            /// </summary>
            [RepositoryItemInfo("333abdd0-105e-426f-9f44-fef60610cea1")]
            public virtual RepoItemInfo TFirstNameInfo
            {
                get
                {
                    return _tfirstnameInfo;
                }
            }

            /// <summary>
            /// The ButtonBOk item.
            /// </summary>
            [RepositoryItem("c11cd780-0d32-4c9e-a507-6eeb7a93ebed")]
            public virtual Ranorex.Button ButtonBOk
            {
                get
                {
                    return _buttonbokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonBOk item info.
            /// </summary>
            [RepositoryItemInfo("c11cd780-0d32-4c9e-a507-6eeb7a93ebed")]
            public virtual RepoItemInfo ButtonBOkInfo
            {
                get
                {
                    return _buttonbokInfo;
                }
            }

            /// <summary>
            /// The BrakDanych item.
            /// </summary>
            [RepositoryItem("eb0a96b0-c9f5-40af-b1d7-b140370e8599")]
            public virtual Ranorex.Picture BrakDanych
            {
                get
                {
                    return _brakdanychInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The BrakDanych item info.
            /// </summary>
            [RepositoryItemInfo("eb0a96b0-c9f5-40af-b1d7-b140370e8599")]
            public virtual RepoItemInfo BrakDanychInfo
            {
                get
                {
                    return _brakdanychInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("dd27a84b-9df6-4840-8c2e-eec629604f23")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("dd27a84b-9df6-4840-8c2e-eec629604f23")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The DaneZostałtyZapisane item.
            /// </summary>
            [RepositoryItem("7e094e00-4f17-401a-8ca9-15f567d1d048")]
            public virtual Ranorex.Text DaneZostałtyZapisane
            {
                get
                {
                    return _danezostałtyzapisaneInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DaneZostałtyZapisane item info.
            /// </summary>
            [RepositoryItemInfo("7e094e00-4f17-401a-8ca9-15f567d1d048")]
            public virtual RepoItemInfo DaneZostałtyZapisaneInfo
            {
                get
                {
                    return _danezostałtyzapisaneInfo;
                }
            }

            /// <summary>
            /// The TLastName item.
            /// </summary>
            [RepositoryItem("2fb17244-f29b-4228-95e2-266a0df2fc7e")]
            public virtual Ranorex.Text TLastName
            {
                get
                {
                    return _tlastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TLastName item info.
            /// </summary>
            [RepositoryItemInfo("2fb17244-f29b-4228-95e2-266a0df2fc7e")]
            public virtual RepoItemInfo TLastNameInfo
            {
                get
                {
                    return _tlastnameInfo;
                }
            }

            /// <summary>
            /// The TStatus item.
            /// </summary>
            [RepositoryItem("08f711e1-71d8-4024-9969-76886a2fc684")]
            public virtual Ranorex.Text TStatus
            {
                get
                {
                    return _tstatusInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TStatus item info.
            /// </summary>
            [RepositoryItemInfo("08f711e1-71d8-4024-9969-76886a2fc684")]
            public virtual RepoItemInfo TStatusInfo
            {
                get
                {
                    return _tstatusInfo;
                }
            }

            /// <summary>
            /// The DBeginDate item.
            /// </summary>
            [RepositoryItem("78fbac79-a3b7-44ef-9e3a-bca2519e9fe8")]
            public virtual Ranorex.DateTime DBeginDate
            {
                get
                {
                    return _dbegindateInfo.CreateAdapter<Ranorex.DateTime>(true);
                }
            }

            /// <summary>
            /// The DBeginDate item info.
            /// </summary>
            [RepositoryItemInfo("78fbac79-a3b7-44ef-9e3a-bca2519e9fe8")]
            public virtual RepoItemInfo DBeginDateInfo
            {
                get
                {
                    return _dbegindateInfo;
                }
            }

            /// <summary>
            /// The BCalculator item.
            /// </summary>
            [RepositoryItem("6d68d03d-f2e5-4d84-8bbf-eaea50194478")]
            public virtual Ranorex.Button BCalculator
            {
                get
                {
                    return _bcalculatorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BCalculator item info.
            /// </summary>
            [RepositoryItemInfo("6d68d03d-f2e5-4d84-8bbf-eaea50194478")]
            public virtual RepoItemInfo BCalculatorInfo
            {
                get
                {
                    return _bcalculatorInfo;
                }
            }

            /// <summary>
            /// The None item.
            /// </summary>
            [RepositoryItem("00c53744-d967-4974-8dcc-09c4754ed002")]
            public virtual Ranorex.Text None
            {
                get
                {
                    return _noneInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The None item info.
            /// </summary>
            [RepositoryItemInfo("00c53744-d967-4974-8dcc-09c4754ed002")]
            public virtual RepoItemInfo NoneInfo
            {
                get
                {
                    return _noneInfo;
                }
            }
        }

        /// <summary>
        /// The AssecoCSharpSampleAppFolder folder.
        /// </summary>
        [RepositoryFolder("9132383b-7ac8-4e49-bfbd-bcac0287c923")]
        public partial class AssecoCSharpSampleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _sysmonthcal32Info;

            /// <summary>
            /// Creates a new AssecoCSharpSample  folder.
            /// </summary>
            public AssecoCSharpSampleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AssecoCSharpSample", "/form[@title='' and @processname='Asseco.CSharp.Sample']", parentFolder, 30000, null, true, "9132383b-7ac8-4e49-bfbd-bcac0287c923", "")
            {
                _sysmonthcal32Info = new RepoItemInfo(this, "SysMonthCal32", "element[@class='SysMonthCal32']", 30000, null, "52432aba-ec36-43e9-b4bf-66b1a1e5bcb2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9132383b-7ac8-4e49-bfbd-bcac0287c923")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9132383b-7ac8-4e49-bfbd-bcac0287c923")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SysMonthCal32 item.
            /// </summary>
            [RepositoryItem("52432aba-ec36-43e9-b4bf-66b1a1e5bcb2")]
            public virtual Ranorex.Unknown SysMonthCal32
            {
                get
                {
                    return _sysmonthcal32Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SysMonthCal32 item info.
            /// </summary>
            [RepositoryItemInfo("52432aba-ec36-43e9-b4bf-66b1a1e5bcb2")]
            public virtual RepoItemInfo SysMonthCal32Info
            {
                get
                {
                    return _sysmonthcal32Info;
                }
            }
        }

        /// <summary>
        /// The FrmCalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("95ccc7a7-3fc7-42a5-8536-86f5b99f257d")]
        public partial class FrmCalculatorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _text1Info;
            RepoItemInfo _zużycieenergiiInfo;
            RepoItemInfo _bcalculateInfo;
            RepoItemInfo _zamknijInfo;
            RepoItemInfo _tconsumtionInfo;
            RepoItemInfo _trateInfo;
            RepoItemInfo _tresultInfo;

            /// <summary>
            /// Creates a new FrmCalculator  folder.
            /// </summary>
            public FrmCalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FrmCalculator", "/form[@controlname='FrmCalculator']", parentFolder, 30000, null, true, "95ccc7a7-3fc7-42a5-8536-86f5b99f257d", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "text[@controlname='tConsumtion']/text[@accessiblerole='Text']", 30000, null, "3a11393d-3f82-45be-b87d-888f2876de44");
                _text1Info = new RepoItemInfo(this, "Text1", "text[@controlname='tRate']/text[@accessiblerole='Text']", 30000, null, "5dca4124-8fc5-4406-a713-ec02291d3750");
                _zużycieenergiiInfo = new RepoItemInfo(this, "ZużycieEnergii", "?/?/text[@accessiblename='Zużycie energii']", 30000, null, "84d8b7e6-db4d-41c1-a1f7-18171af62fd9");
                _bcalculateInfo = new RepoItemInfo(this, "BCalculate", "button[@controlname='bCalculate']", 30000, null, "0dc06e51-b33d-4ddc-8107-809040685641");
                _zamknijInfo = new RepoItemInfo(this, "Zamknij", "?/?/button[@accessiblename='Zamknij']", 30000, null, "36c8afaa-90de-4671-8c09-b3592e0fdc35");
                _tconsumtionInfo = new RepoItemInfo(this, "TConsumtion", "text[@controlname='tConsumtion']", 30000, null, "bdb098c7-e196-4b88-ac55-687389179758");
                _trateInfo = new RepoItemInfo(this, "TRate", "text[@controlname='tRate']", 30000, null, "8f0a686d-2e23-4641-9b82-8e71a0f80c42");
                _tresultInfo = new RepoItemInfo(this, "TResult", "text[@controlname='tResult']", 30000, null, "4dbdd587-5aad-4529-a447-afdac6e907b8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("95ccc7a7-3fc7-42a5-8536-86f5b99f257d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("95ccc7a7-3fc7-42a5-8536-86f5b99f257d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("3a11393d-3f82-45be-b87d-888f2876de44")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("3a11393d-3f82-45be-b87d-888f2876de44")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("5dca4124-8fc5-4406-a713-ec02291d3750")]
            public virtual Ranorex.Text Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("5dca4124-8fc5-4406-a713-ec02291d3750")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }

            /// <summary>
            /// The ZużycieEnergii item.
            /// </summary>
            [RepositoryItem("84d8b7e6-db4d-41c1-a1f7-18171af62fd9")]
            public virtual Ranorex.Text ZużycieEnergii
            {
                get
                {
                    return _zużycieenergiiInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ZużycieEnergii item info.
            /// </summary>
            [RepositoryItemInfo("84d8b7e6-db4d-41c1-a1f7-18171af62fd9")]
            public virtual RepoItemInfo ZużycieEnergiiInfo
            {
                get
                {
                    return _zużycieenergiiInfo;
                }
            }

            /// <summary>
            /// The BCalculate item.
            /// </summary>
            [RepositoryItem("0dc06e51-b33d-4ddc-8107-809040685641")]
            public virtual Ranorex.Button BCalculate
            {
                get
                {
                    return _bcalculateInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BCalculate item info.
            /// </summary>
            [RepositoryItemInfo("0dc06e51-b33d-4ddc-8107-809040685641")]
            public virtual RepoItemInfo BCalculateInfo
            {
                get
                {
                    return _bcalculateInfo;
                }
            }

            /// <summary>
            /// The Zamknij item.
            /// </summary>
            [RepositoryItem("36c8afaa-90de-4671-8c09-b3592e0fdc35")]
            public virtual Ranorex.Button Zamknij
            {
                get
                {
                    return _zamknijInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Zamknij item info.
            /// </summary>
            [RepositoryItemInfo("36c8afaa-90de-4671-8c09-b3592e0fdc35")]
            public virtual RepoItemInfo ZamknijInfo
            {
                get
                {
                    return _zamknijInfo;
                }
            }

            /// <summary>
            /// The TConsumtion item.
            /// </summary>
            [RepositoryItem("bdb098c7-e196-4b88-ac55-687389179758")]
            public virtual Ranorex.Text TConsumtion
            {
                get
                {
                    return _tconsumtionInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TConsumtion item info.
            /// </summary>
            [RepositoryItemInfo("bdb098c7-e196-4b88-ac55-687389179758")]
            public virtual RepoItemInfo TConsumtionInfo
            {
                get
                {
                    return _tconsumtionInfo;
                }
            }

            /// <summary>
            /// The TRate item.
            /// </summary>
            [RepositoryItem("8f0a686d-2e23-4641-9b82-8e71a0f80c42")]
            public virtual Ranorex.Text TRate
            {
                get
                {
                    return _trateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TRate item info.
            /// </summary>
            [RepositoryItemInfo("8f0a686d-2e23-4641-9b82-8e71a0f80c42")]
            public virtual RepoItemInfo TRateInfo
            {
                get
                {
                    return _trateInfo;
                }
            }

            /// <summary>
            /// The TResult item.
            /// </summary>
            [RepositoryItem("4dbdd587-5aad-4529-a447-afdac6e907b8")]
            public virtual Ranorex.Text TResult
            {
                get
                {
                    return _tresultInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TResult item info.
            /// </summary>
            [RepositoryItemInfo("4dbdd587-5aad-4529-a447-afdac6e907b8")]
            public virtual RepoItemInfo TResultInfo
            {
                get
                {
                    return _tresultInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}