///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Asseco.CSharp.Sample.Tests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("25203bee-2a47-4446-9973-ebd320c26a10", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Asseco_CSharp_Sample_TestsRepository repository.
        /// </summary>
        public static Asseco_CSharp_Sample_TestsRepository repo = Asseco_CSharp_Sample_TestsRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Users\\Slawomir.Marlewski\\source\\repos\\Asseco.CSharp\\Asseco.CSharp.Sample\\bin\\Debug\\Asseco.CSharp.Sample.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Users\\Slawomir.Marlewski\\source\\repos\\Asseco.CSharp\\Asseco.CSharp.Sample\\bin\\Debug\\Asseco.CSharp.Sample.exe", "", "C:\\Users\\Slawomir.Marlewski\\source\\repos\\Asseco.CSharp\\Asseco.CSharp.Sample\\bin\\Debug", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.ButtonBOk' at 29;13.", repo.FrmMain.ButtonBOkInfo, new RecordItemIndex(1));
            repo.FrmMain.ButtonBOk.Click("29;13");
            Delay.Milliseconds(200);
            
            TestValidateStatus();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.DaneZostałtyZapisane' at 57;7.", repo.FrmMain.DaneZostałtyZapisaneInfo, new RecordItemIndex(3));
            repo.FrmMain.DaneZostałtyZapisane.Click("57;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '' with focus on 'FrmMain.TFirstName'.", repo.FrmMain.TFirstNameInfo, new RecordItemIndex(4));
            repo.FrmMain.TFirstName.PressKeys("");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'FrmMain.DaneZostałtyZapisane' at 33;9.", repo.FrmMain.DaneZostałtyZapisaneInfo, new RecordItemIndex(5));
            repo.FrmMain.DaneZostałtyZapisane.MoveTo("33;9");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'FrmMain.DaneZostałtyZapisane' at 33;9.", repo.FrmMain.DaneZostałtyZapisaneInfo, new RecordItemIndex(6));
            repo.FrmMain.DaneZostałtyZapisane.MoveTo("33;9");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Dane zostały zapisane.') on item 'FrmMain.TStatus'.", repo.FrmMain.TStatusInfo, new RecordItemIndex(7));
            Validate.Attribute(repo.FrmMain.TStatusInfo, "Text", "Dane zostały zapisane.");
            Delay.Milliseconds(0);
            
            TestValidateFirstName();
            Delay.Milliseconds(0);
            
            TestValidateLastName();
            Delay.Milliseconds(0);
            
            ValidatePeriod();
            Delay.Milliseconds(0);
            
            OpenFileTest();
            Delay.Milliseconds(0);
            
            TestEnableCalculateButton();
            Delay.Milliseconds(0);
            
            WordsTest();
            Delay.Milliseconds(0);
            
            TestDb();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmMain.BCalculator' at 36;16.", repo.FrmMain.BCalculatorInfo, new RecordItemIndex(15));
            //repo.FrmMain.BCalculator.Click("36;16");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCalculator.Text' at 31;10.", repo.FrmCalculator.TextInfo, new RecordItemIndex(16));
            //repo.FrmCalculator.Text.Click("31;10");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '123' with focus on 'FrmCalculator.Text'.", repo.FrmCalculator.TextInfo, new RecordItemIndex(17));
            //repo.FrmCalculator.Text.PressKeys("123");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCalculator.Text1' at 12;15.", repo.FrmCalculator.Text1Info, new RecordItemIndex(18));
            //repo.FrmCalculator.Text1.Click("12;15");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.1{Back}{Back}0,1' with focus on 'FrmCalculator.Text1'.", repo.FrmCalculator.Text1Info, new RecordItemIndex(19));
            //repo.FrmCalculator.Text1.PressKeys(".1{Back}{Back}0,1");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCalculator.ZużycieEnergii' at 48;10.", repo.FrmCalculator.ZużycieEnergiiInfo, new RecordItemIndex(20));
            //repo.FrmCalculator.ZużycieEnergii.Click("48;10");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCalculator.BCalculate' at 37;11.", repo.FrmCalculator.BCalculateInfo, new RecordItemIndex(21));
            //repo.FrmCalculator.BCalculate.Click("37;11");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmCalculator.Zamknij' at 21;8.", repo.FrmCalculator.ZamknijInfo, new RecordItemIndex(22));
            repo.FrmCalculator.Zamknij.Click("21;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'FrmMain'.", repo.FrmMain.SelfInfo, new RecordItemIndex(23));
            Host.Current.CloseApplication(repo.FrmMain.Self, 100);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
